### ISSUE TITLE
num_pages is deprecated and will be removed in Kaminari 1.0

### ISSUE THREAD

**Issue by gsreynolds** [jgraichen/paginate-responder#8]
From Kaminari 0.1.7 num_pages is deprecated and replaced by total_pages: https://github.com/amatsuda/kaminari/blob/master/CHANGELOG.rdoc#0170

total_pages method in the kaminari adapter will need amended, perhaps with backwards compat for < 0.1.7?

```
    def total_pages
      resource.num_pages if resource.respond_to? :num_pages
    end
```

https://github.com/jgraichen/paginate-responder/blob/d1a3a91ae0eeb92c4d69db02aa57a155c01604b1/lib/paginate-responder/adapter/kaminari_adapter.rb#L23

I can PR if you would prefer.

**Comment by jgraichen** [comment]
Has been fixed.
