### ISSUE TITLE
Paginate only on index

### ISSUE THREAD

**Issue by franzliedke** [jgraichen/paginate-responder#9]
As per observation and from how I understand [the source code](https://github.com/jgraichen/paginate-responder/blob/3b759ecb3aacfce6bf68bdd5c9562cbea689aadc/lib/responders/paginate_responder.rb#L4), it seems like the `PaginateResponder` is active on all GET routes.

IMO, this should only happen on `index`, not `show` (at least in a classical Rails resource controller). Paginating member resources has no semantic meaning.

**Comment by jgraichen** [comment]
This is nothing the responder can (easily) know and do as it only handles a response object. Using a responder on a single action is something only the controller may be able to do.

**Comment by franzliedke** [comment]
But the responder has access to the controller - it should be able to find out which action is being requested? There is `controller.action_name`, I believe.

If you don't like that, how about checking whether the controller implements something like `respond_with_pagination?`, which, if implemented, determines whether the current response should be paginated?

**Comment by jgraichen** [comment]
I think the proper way would be to use `respond_with resource, responder: NonPaginatingResponder`. If you need multiple responders you cannot use a single class-side responder class anyway.

I will also evaluate passing an option to disable pagination. Feel free to experiment too and open PRs.

**Comment by franzliedke** [comment]
@jgraichen Sorry to resurrect an old conversation. Shouldn't something like this be possible as well (downside: it would have to be done explicitly in every controller).

~~~rb
responders PaginationResponder, only: :index
~~~

**Comment by franzliedke** [comment]
Apparently that's not possible with `responders`. Weird, I thought I had seen this possibility somewhere in the source.

**Comment by franzliedke** [comment]
@jgraichen What do you think about separating plural from singular controllers? E.g. having a `CustomersController` for the `/customers` routes (GET and POST) as well as a `CustomerController` for `/customers/:id` (GET, PUT/PATCH, DELETE).

There is usually no relevant code reuse between plural and singular actions anyway, which IMO is the only relevant argument for munging all these actions into one controller anyway. (Aside from the "This is Rails convention" thing, obviously...)

Asking here because this would nicely fix the problem discussed in this issue, without any hacks. `PaginateResponder` would only be included in the plural controllers for each resource.
